---
- name: Update all packages to the latest version
  apt:
    upgrade: dist
   
- name: Install packages
  apt: 
    pkg: "{{ item }}"
    state: present
  with_items:
    - git

# installing node.js
- name: Add the NodeSource package signing key
  apt_key:
    url: "{{ node_key }}"
    validate_certs: no
    state: present

- name: Add nodejs repo
  apt_repository:
    repo: "{{node_repo}}"
    state: present

- name: Install nodejs
  apt:
    pkg: nodejs
    state: present

- name: Install forever
  npm:
    name: forever
    global: yes
    state: present

- name: Clone git repo
  git:
    repo: "https://{{ lookup('env', 'CLONE_TOKEN') }}@github.ncsu.edu/sbshete/CSC-510-Project.git"
    dest: "{{ app_dest }}"
    force: yes
    version: milestone-deploy

- name: Install local node modules
  shell: cd {{ app_dest }}/js && npm install

- name: Install MySQL
  apt:
    pkg: mysql-server
    state: latest
    force: yes
    update_cache: yes

- name: Restart MySQL
  service:
    name: mysql
    state: started

- name: Wait for MySQL to start on default port
  wait_for:
    port: 3306

- name: Remove case sensitivity in MySQL
  blockinfile:
   path: "{{ mysqlconfig}}"
   insertafter: \[mysqld\]
   block: |
     lower_case_table_names=1

- name: Restart MySQL
  systemd:
   name: mysql
   state: restarted

- name: Run db.sql
  shell: "mysql < {{ app_dest }}/database/db.sql"

- name: Restart MySQL
  systemd:
   name: mysql
   state: restarted

- name: Set environment variables
  become: yes
  become_method: sudo
  blockinfile:
    path: /etc/environment
    block: | 
      export GITHUB_TOKEN={{ lookup('env', 'GITHUB_TOKEN') }}
      export BOT_TOKEN={{ lookup('env', 'BOT_TOKEN') }}
      export USER_TOKEN={{ lookup('env', 'USER_TOKEN') }}
      export PASS_TOKEN={{ lookup('env', 'PASS_TOKEN') }}
    create: yes
    state: present

- name: Stop all forever scripts
  command: forever stopall

- name: Start server.js using forever
  command: forever start server.js
  args:
    chdir: "{{ app_dest }}/js"

- name: Start traziBot.js using forever
  command: forever start traziBot.js
  args:
    chdir: "{{ app_dest }}/js"


